env: standard
runtime: nodejs18
service: default
automatic_scaling:
    min_idle_instances: 1
    min_instances: 1
handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  NODE_ENV: production
  MONGODB_URI: mongodb+srv://eliperel20:L4ebUmuPQqSAqrRc@cluster0.rupsaoq.mongodb.net/taskdb?retryWrites=true&w=majority

