runtime: nodejs14
service: task-app-nestjs

env_variables:
  NODE_ENV: production
  MONGODB_URI: mongodb+srv://eliperel20:L4ebUmuPQqSAqrRc@cluster0.rupsaoq.mongodb.net/taskdb?retryWrites=true&w=majority

handlers:
  - url: /.*
    script: auto
    secure: always
